Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

RegexpLiteral:
  Enabled: false

AllCops:
  Excludes:
    - db/schema.rb
    - Guardfile

StringLiterals:
  Enabled: false

HashSyntax:
  Enabled: false

SpaceInsideHashLiteralBraces:
  Enabled: false
